REM   Script: Q2-REVIZE
REM   Q2-REVIZE

WITH nEW_TABLE AS ( SELECT X.LOCATION_ID, D.DEPARTMENT_ID 
             FROM HR.LOCATIONS X 
             JOIN HR.DEPARTMENTS D 
             ON X.LOCATION_ID = D.LOCATION_ID) 
 
SELECT nEW_TABLE.LOCATION_ID, COUNT(E.EMPLOYEE_ID) 
FROM nEW_TABLE 
JOIN HR.EMPLOYEES E  
ON nEW_TABLE.DEPARTMENT_ID = E.DEPARTMENT_ID 
GROUP BY nEW_TABLE.LOCATION_ID 



