REM   Script: Q4
REM   Q4

WITH tABLE1 AS ( SELECT D.DEPARTMENT_ID, E.EMPLOYEE_ID 
FROM HR.DEPARTMENTS D 
FULL OUTER JOIN HR.EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
WHERE E.EMPLOYEE_ID IS NULL) 
 
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME,  
(SUBSTR(D.DEPARTMENT_NAME,-1,1) || SUBSTR(D.DEPARTMENT_NAME,-2,1)) || SUBSTR(D.DEPARTMENT_NAME,-3,1) AS RETURNEDVALUE, tABLE1.EMPLOYEE_ID 
FROM tABLE1 
JOIN HR.DEPARTMENTS D  
ON tABLE1.DEPARTMENT_ID = D.DEPARTMENT_ID 



