REM   Script: Q1
REM   Q1

WITH SALARIES_RANKS AS ( 
SELECT E.FIRST_NAME, 
 E.LAST_NAME, 
 D.DEPARTMENT_NAME, 
 E.SALARY, 
 ROW_NUMBER() OVER (PARTITION BY D.DEPARTMENT_ID ORDER BY SALARY DESC 
 ) AS SALARY_RANK 
FROM HR.DEPARTMENT D JOIN HR.EMPLOYEEs E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
) 
  
SELECT * 
FROM SALARIES_RANKS 
WHERE SALARY_RANK = 1


